// src/utils/pdfGenerator.js
import PDFDocument from "pdfkit";

/**
 * Generate PDF from note content
 * @param {object} note - Note object
 * @returns {Buffer} PDF buffer
 */
export const generatePDF = (note) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });

      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(note.title, { align: "center" });

      doc.moveDown();
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Created: ${new Date(note.createdAt).toLocaleDateString()}`, {
          align: "center",
        });

      if (note.tags && note.tags.length > 0) {
        doc.text(`Tags: ${note.tags.join(", ")}`, { align: "center" });
      }

      doc.moveDown(2);

      // Summary section
      if (note.structuredNotes?.summary) {
        doc.fontSize(16).font("Helvetica-Bold").text("Summary");
        doc.moveDown(0.5);
        doc
          .fontSize(11)
          .font("Helvetica")
          .text(note.structuredNotes.summary, { align: "justify" });
        doc.moveDown(1.5);
      }

      // Key Points section
      if (
        note.structuredNotes?.keyPoints &&
        note.structuredNotes.keyPoints.length > 0
      ) {
        doc.fontSize(16).font("Helvetica-Bold").text("Key Points");
        doc.moveDown(0.5);
        doc.fontSize(11).font("Helvetica");

        note.structuredNotes.keyPoints.forEach((point, index) => {
          doc.text(`${index + 1}. ${point}`, { indent: 20 });
          doc.moveDown(0.3);
        });
        doc.moveDown(1);
      }

      // Detailed sections
      if (
        note.structuredNotes?.sections &&
        note.structuredNotes.sections.length > 0
      ) {
        doc.fontSize(16).font("Helvetica-Bold").text("Detailed Notes");
        doc.moveDown(1);

        note.structuredNotes.sections.forEach((section) => {
          doc.fontSize(14).font("Helvetica-Bold").text(section.heading);
          doc.moveDown(0.5);
          doc
            .fontSize(11)
            .font("Helvetica")
            .text(section.content, { align: "justify" });
          doc.moveDown(1);
        });
      } else {
        // Fallback to plain content
        doc
          .fontSize(11)
          .font("Helvetica")
          .text(note.content, { align: "justify" });
      }

      // Footer
      doc
        .fontSize(8)
        .font("Helvetica")
        .text("Generated by EduNote", 50, doc.page.height - 50, {
          align: "center",
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Generate TXT from note content
 * @param {object} note - Note object
 * @returns {string} Text content
 */
export const generateTXT = (note) => {
  let text = "";

  // Header
  text += `${note.title}\n`;
  text += `${"=".repeat(note.title.length)}\n\n`;
  text += `Created: ${new Date(note.createdAt).toLocaleDateString()}\n`;

  if (note.tags && note.tags.length > 0) {
    text += `Tags: ${note.tags.join(", ")}\n`;
  }
  text += "\n";

  // Summary
  if (note.structuredNotes?.summary) {
    text += "SUMMARY\n";
    text += "-------\n";
    text += `${note.structuredNotes.summary}\n\n`;
  }

  // Key Points
  if (
    note.structuredNotes?.keyPoints &&
    note.structuredNotes.keyPoints.length > 0
  ) {
    text += "KEY POINTS\n";
    text += "----------\n";
    note.structuredNotes.keyPoints.forEach((point, index) => {
      text += `${index + 1}. ${point}\n`;
    });
    text += "\n";
  }

  // Detailed sections
  if (
    note.structuredNotes?.sections &&
    note.structuredNotes.sections.length > 0
  ) {
    text += "DETAILED NOTES\n";
    text += "--------------\n\n";

    note.structuredNotes.sections.forEach((section) => {
      text += `## ${section.heading}\n\n`;
      text += `${section.content}\n\n`;
    });
  } else {
    text += note.content;
  }

  text += "\n---\nGenerated by EduNote\n";

  return text;
};

/**
 * Generate Markdown from note content
 * @param {object} note - Note object
 * @returns {string} Markdown content
 */
export const generateMarkdown = (note) => {
  let markdown = "";

  // Header
  markdown += `# ${note.title}\n\n`;
  markdown += `**Created:** ${new Date(note.createdAt).toLocaleDateString()}\n`;

  if (note.tags && note.tags.length > 0) {
    markdown += `**Tags:** ${note.tags
      .map((tag) => `\`${tag}\``)
      .join(", ")}\n`;
  }
  markdown += "\n---\n\n";

  // Summary
  if (note.structuredNotes?.summary) {
    markdown += "## Summary\n\n";
    markdown += `${note.structuredNotes.summary}\n\n`;
  }

  // Key Points
  if (
    note.structuredNotes?.keyPoints &&
    note.structuredNotes.keyPoints.length > 0
  ) {
    markdown += "## Key Points\n\n";
    note.structuredNotes.keyPoints.forEach((point) => {
      markdown += `- ${point}\n`;
    });
    markdown += "\n";
  }

  // Detailed sections
  if (
    note.structuredNotes?.sections &&
    note.structuredNotes.sections.length > 0
  ) {
    markdown += "## Detailed Notes\n\n";

    note.structuredNotes.sections.forEach((section) => {
      markdown += `### ${section.heading}\n\n`;
      markdown += `${section.content}\n\n`;
    });
  } else {
    markdown += note.content;
  }

  markdown += "\n---\n*Generated by EduNote*\n";

  return markdown;
};
